create table candidate_profiles (
    id bigint generated by default as identity,
    name varchar(160) not null,
    cv_text text not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    primary key (id)
);

create table job_offers (
    id bigint generated by default as identity,
    title varchar(255) not null,
    location varchar(255),
    applicants_count integer,
    description text,
    requirements text,
    company varchar(255),
    min_years_experience integer,
    required_skills_csv text,
    nice_to_have_skills_csv text,
    primary key (id)
);

create table jobs (
    id bigint generated by default as identity,
    source varchar(32) not null,
    external_job_id varchar(255),
    source_url varchar(2048) not null,
    title varchar(512),
    company varchar(256),
    company_logo_url varchar(2048),
    location varchar(256),
    page_title varchar(512),
    tentative_job_title varchar(512),
    status varchar(32) not null,
    description text,
    requirements_text text,
    visible_text text,
    applicants_text varchar(2000),
    applicants_count integer,
    posted_at_text varchar(2000),
    location_raw varchar(2000),
    created_at timestamp(6) with time zone not null,
    primary key (id)
);

create table job_snapshots (
    id bigint generated by default as identity,
    job_id bigint not null,
    source_url varchar(2048) not null,
    title varchar(512),
    company varchar(256),
    location varchar(256),
    visible_text text,
    job_description text,
    applicants_count integer,
    applicants_text varchar(2000),
    posted_at_text varchar(2000),
    location_raw varchar(2000),
    html text,
    plugin_name varchar(64),
    captured_at timestamp(6) with time zone not null,
    primary key (id)
);

create table skills (
    id bigint generated by default as identity,
    name varchar(128) not null,
    name_normalized varchar(128) not null,
    enabled boolean not null,
    primary key (id)
);

create table skill_aliases (
    id bigint generated by default as identity,
    skill_id bigint not null,
    alias varchar(128) not null,
    alias_normalized varchar(128) not null,
    primary key (id)
);

alter table if exists job_snapshots
    add constraint fk_job_snapshots_job_id
    foreign key (job_id)
    references jobs;

alter table if exists skill_aliases
    add constraint fk_skill_aliases_skill_id
    foreign key (skill_id)
    references skills;

create index idx_candidate_profiles_created_at
    on candidate_profiles (created_at);

create index idx_jobs_source_external_job_id
    on jobs (source, external_job_id);

create index idx_jobs_source_url
    on jobs (source_url);

create index idx_job_snapshots_job_id
    on job_snapshots (job_id);

create unique index idx_skills_name_normalized
    on skills (name_normalized);

create index idx_skill_aliases_skill_id
    on skill_aliases (skill_id);

create unique index idx_skill_aliases_alias_normalized
    on skill_aliases (alias_normalized);
