create table document_embeddings (
    id bigint generated by default as identity,
    owner_type varchar(32) not null,
    owner_id bigint not null,
    section_type varchar(64) not null,
    source_text_hash varchar(128) not null,
    embedding_model varchar(128) not null,
    embedding_dimensions integer not null default 1024,
    normalizer_version varchar(64) not null,
    embedding vector(1024),
    status varchar(32) not null default 'PENDING',
    error_message text,
    created_at timestamp(6) with time zone not null default now(),
    updated_at timestamp(6) with time zone not null default now(),
    last_embedded_at timestamp(6) with time zone,
    primary key (id),
    constraint chk_document_embeddings_owner_type
        check (owner_type in ('JOB', 'PROFILE')),
    constraint chk_document_embeddings_status
        check (status in ('PENDING', 'READY', 'FAILED')),
    constraint chk_document_embeddings_embedding_dimensions
        check (embedding_dimensions = 1024),
    constraint uq_document_embeddings_owner_section_model
        unique (owner_type, owner_id, section_type, embedding_model, normalizer_version)
);

create index idx_document_embeddings_owner
    on document_embeddings (owner_type, owner_id);

create index idx_document_embeddings_status
    on document_embeddings (status);

create index idx_document_embeddings_source_text_hash
    on document_embeddings (source_text_hash);

create index idx_document_embeddings_model_dimensions
    on document_embeddings (embedding_model, embedding_dimensions);
