create table candidate_profile_projects (
    id bigint generated by default as identity,
    candidate_profile_id bigint not null,
    title varchar(180) not null,
    description text not null,
    skills_text text,
    evidence_type varchar(32) not null default 'OTHER',
    repository_url varchar(2048),
    demo_url varchar(2048),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    primary key (id)
);

alter table if exists candidate_profile_projects
    add constraint fk_candidate_profile_projects_profile_id
    foreign key (candidate_profile_id)
    references candidate_profiles
    on delete cascade;

create index idx_candidate_profile_projects_profile_created_at
    on candidate_profile_projects (candidate_profile_id, created_at);

create index idx_candidate_profile_projects_evidence_type
    on candidate_profile_projects (evidence_type);
